builds:
  - versionName: "2.0.0"
    versionCode: 2
    commit: 9d21098
    subdir: app
    gradle:
      - release
    forceversion: true
    forcevercode: true
    ndk: 26.1.10909125
    
    # Configuraciones para F-Droid
    sudo:
      - echo "deb https://deb.debian.org/debian trixie main" > /etc/apt/sources.list.d/trixie.list
      - apt-get update
      - apt-get install -y -t trixie openjdk-17-jdk-headless
      - update-alternatives --auto java
      
    # Configuración para evitar archivos innecesarios
    prebuild:
      - echo "Limpiando archivos innecesarios antes del build..."
      - find . -name "*.dll" -delete
      - find . -name "*.dylib" -delete
      - find . -name "*.so.debug" -delete
      - find . -name "*_debug.so" -delete
      - find . -name "*_testing.so" -delete
      - find . -name "*_unstripped.so" -delete
      - echo "Archivos de debug eliminados"
      
    # Deshabilitar verificaciones problemáticas temporalmente
    disable: 
      - ReproducibleBuilds 
      - NonFreeNet 